### ISSUE TITLE
No module named 'training'?

### ISSUE THREAD

**Issue by nerdyrodent** [autonomousvision/voxgraf#2]
python gen_video.py --network pretrained_models/ffhq256.pkl --seeds 0-3 --grid 1x2 --num-keyframes 2 --output ffhq_256_samples/video.mp4 --trunc=0.5

_Traceback (most recent call last):
  File "/home/nerdy/github/voxgraf/gen_video.py", line 20, in <module>
    from training.virtual_camera_utils import uv2RT
ModuleNotFoundError: No module named 'training'_

**Comment by katjaschwarz** [comment]
I added the missing files
